/*
 * pages/agent.ts — the 助手 group: what the assistant is, connecting a key, ordering and oversight,
 * the working record, the region lock, trouble and limits, undo.
 *
 * Descriptor data only: copy uses full i18n key literals, key tables name command ids and figures
 * name renderable help scenes or surfaces.
 */
import type { HelpPage } from '../page-schema';

export const AGENT_PAGES: readonly HelpPage[] = [
  {
    id: 'agent-intro',
    group: 'agent',
    titleKey: 'help.agentintro.title',
    navKey: 'help.agentintro.nav',
    ledeKey: 'help.agentintro.lede',
    entryKey: 'help.agentintro.entry',
    figure: { kind: 'surface', surface: 'agent-dream', captionKey: 'help.agentintro.figcap' },
    sections: [
      { kind: 'prose', anchor: 'agintro-what', titleKey: 'help.agentintro.what_t', bodyKeys: ['help.agentintro.what_b1'] },
      { kind: 'prose', anchor: 'agintro-can', titleKey: 'help.agentintro.can_t', bodyKeys: ['help.agentintro.can_b1', 'help.agentintro.can_b2'] },
      { kind: 'prose', anchor: 'agintro-cannot', titleKey: 'help.agentintro.cannot_t', bodyKeys: ['help.agentintro.cannot_b1'] },
      { kind: 'prose', anchor: 'agintro-where', titleKey: 'help.agentintro.where_t', bodyKeys: ['help.agentintro.where_b1'] },
      { kind: 'prose', anchor: 'agintro-privacy', titleKey: 'help.agentintro.privacy_t', bodyKeys: ['help.agentintro.privacy_b1'] },
      { kind: 'prose', anchor: 'agintro-record', titleKey: 'help.agentintro.record_t', bodyKeys: ['help.agentintro.record_b1'] },
    ],
    qa: [
      { qKey: 'help.agentintro.q1', aKey: 'help.agentintro.a1' },
      { qKey: 'help.agentintro.q2', aKey: 'help.agentintro.a2' },
      { qKey: 'help.agentintro.q3', aKey: 'help.agentintro.a3' },
      { qKey: 'help.agentintro.q4', aKey: 'help.agentintro.a4' },
    ],
    seeAlso: ['agent-setup', 'agent-run', 'agent-trail'],
  },
  {
    id: 'agent-setup',
    group: 'agent',
    titleKey: 'help.agentsetup.title',
    ledeKey: 'help.agentsetup.lede',
    entryKey: 'help.agentsetup.entry',
    figure: { kind: 'surface', surface: 'agent-setup', captionKey: 'help.agentsetup.figcap' },
    sections: [
      { kind: 'prose', anchor: 'agsetup-providers', titleKey: 'help.agentsetup.providers_t', bodyKeys: ['help.agentsetup.providers_b1'] },
      {
        kind: 'steps', anchor: 'agsetup-keys', titleKey: 'help.agentsetup.keys_t', bodyKeys: ['help.agentsetup.keys_b1'],
        groups: [
          { provider: 'claude', stepKeys: ['help.agentsetup.keys_claude_1', 'help.agentsetup.keys_claude_2', 'help.agentsetup.keys_claude_3', 'help.agentsetup.keys_claude_4'] },
          { provider: 'openai', stepKeys: ['help.agentsetup.keys_openai_1', 'help.agentsetup.keys_openai_2', 'help.agentsetup.keys_openai_3', 'help.agentsetup.keys_openai_4'] },
          { provider: 'deepseek', stepKeys: ['help.agentsetup.keys_deepseek_1', 'help.agentsetup.keys_deepseek_2', 'help.agentsetup.keys_deepseek_3', 'help.agentsetup.keys_deepseek_4'] },
          { provider: 'gemini', stepKeys: ['help.agentsetup.keys_gemini_1', 'help.agentsetup.keys_gemini_2', 'help.agentsetup.keys_gemini_3'] },
          { provider: 'openrouter', stepKeys: ['help.agentsetup.keys_openrouter_1', 'help.agentsetup.keys_openrouter_2', 'help.agentsetup.keys_openrouter_3'] },
          { provider: 'zhipu', stepKeys: ['help.agentsetup.keys_zhipu_1', 'help.agentsetup.keys_zhipu_2', 'help.agentsetup.keys_zhipu_3'] },
          { provider: 'qwen', stepKeys: ['help.agentsetup.keys_qwen_1', 'help.agentsetup.keys_qwen_2', 'help.agentsetup.keys_qwen_3', 'help.agentsetup.keys_qwen_4'] },
          { provider: 'moonshot', stepKeys: ['help.agentsetup.keys_moonshot_1', 'help.agentsetup.keys_moonshot_2', 'help.agentsetup.keys_moonshot_3'] },
          { provider: 'doubao', stepKeys: ['help.agentsetup.keys_doubao_1', 'help.agentsetup.keys_doubao_2', 'help.agentsetup.keys_doubao_3'] },
          { provider: 'perplexity', stepKeys: ['help.agentsetup.keys_perplexity_1', 'help.agentsetup.keys_perplexity_2', 'help.agentsetup.keys_perplexity_3', 'help.agentsetup.keys_perplexity_4'] },
        ],
      },
      { kind: 'prose', anchor: 'agsetup-paste', titleKey: 'help.agentsetup.paste_t', bodyKeys: ['help.agentsetup.paste_b1'], figure: { kind: 'surface', surface: 'agent-setup-detect', captionKey: 'help.agentsetup.detect_figcap' } },
      { kind: 'prose', anchor: 'agsetup-unknown', titleKey: 'help.agentsetup.unknown_t', bodyKeys: ['help.agentsetup.unknown_b1'] },
      { kind: 'prose', anchor: 'agsetup-model', titleKey: 'help.agentsetup.model_t', bodyKeys: ['help.agentsetup.model_b1'] },
      { kind: 'prose', anchor: 'agsetup-custom', titleKey: 'help.agentsetup.custom_t', bodyKeys: ['help.agentsetup.custom_b1'] },
      { kind: 'prose', anchor: 'agsetup-safety', titleKey: 'help.agentsetup.safety_t', bodyKeys: ['help.agentsetup.safety_b1'] },
      { kind: 'prose', anchor: 'agsetup-manage', titleKey: 'help.agentsetup.manage_t', bodyKeys: ['help.agentsetup.manage_b1'] },
    ],
    qa: [
      { qKey: 'help.agentsetup.q1', aKey: 'help.agentsetup.a1' },
      { qKey: 'help.agentsetup.q2', aKey: 'help.agentsetup.a2' },
      { qKey: 'help.agentsetup.q3', aKey: 'help.agentsetup.a3' },
      { qKey: 'help.agentsetup.q4', aKey: 'help.agentsetup.a4' },
      { qKey: 'help.agentsetup.q5', aKey: 'help.agentsetup.a5' },
      { qKey: 'help.agentsetup.q6', aKey: 'help.agentsetup.a6' },
    ],
    seeAlso: ['agent-intro', 'agent-run', 'agent-trouble', 'settings'],
  },
  {
    id: 'agent-run',
    group: 'agent',
    titleKey: 'help.agentrun.title',
    ledeKey: 'help.agentrun.lede',
    entryKey: 'help.agentrun.entry',
    figure: { kind: 'surface', surface: 'agent-plan', captionKey: 'help.agentrun.figcap' },
    sections: [
      { kind: 'prose', anchor: 'agrun-order', titleKey: 'help.agentrun.order_t', bodyKeys: ['help.agentrun.order_b1', 'help.agentrun.order_b2'] },
      { kind: 'prose', anchor: 'agrun-oversight', titleKey: 'help.agentrun.oversight_t', bodyKeys: ['help.agentrun.oversight_b1'], figure: { kind: 'surface', surface: 'agent-oversight', captionKey: 'help.agentrun.oversight_figcap' } },
      { kind: 'prose', anchor: 'agrun-plan', titleKey: 'help.agentrun.plan_t', bodyKeys: ['help.agentrun.plan_b1', 'help.agentrun.plan_b2'] },
      { kind: 'prose', anchor: 'agrun-steer', titleKey: 'help.agentrun.steer_t', bodyKeys: ['help.agentrun.steer_b1'], figure: { kind: 'surface', surface: 'agent-steer', captionKey: 'help.agentrun.steer_figcap' } },
      { kind: 'prose', anchor: 'agrun-stop', titleKey: 'help.agentrun.stop_t', bodyKeys: ['help.agentrun.stop_b1', 'help.agentrun.stop_b2'] },
      { kind: 'prose', anchor: 'agrun-idle', titleKey: 'help.agentrun.idle_t', bodyKeys: ['help.agentrun.idle_b1'] },
    ],
    qa: [
      { qKey: 'help.agentrun.q1', aKey: 'help.agentrun.a1' },
      { qKey: 'help.agentrun.q2', aKey: 'help.agentrun.a2' },
      { qKey: 'help.agentrun.q3', aKey: 'help.agentrun.a3' },
      { qKey: 'help.agentrun.q4', aKey: 'help.agentrun.a4' },
    ],
    seeAlso: ['agent-intro', 'agent-trail', 'agent-region', 'agent-undo'],
  },
  {
    id: 'agent-trail',
    group: 'agent',
    titleKey: 'help.agenttrail.title',
    navKey: 'help.agenttrail.nav',
    ledeKey: 'help.agenttrail.lede',
    entryKey: 'help.agenttrail.entry',
    figure: { kind: 'surface', surface: 'agent-trail', captionKey: 'help.agenttrail.figcap' },
    sections: [
      { kind: 'prose', anchor: 'agtrail-ticket', titleKey: 'help.agenttrail.ticket_t', bodyKeys: ['help.agenttrail.ticket_b1'] },
      { kind: 'prose', anchor: 'agtrail-ops', titleKey: 'help.agenttrail.ops_t', bodyKeys: ['help.agenttrail.ops_b1', 'help.agenttrail.ops_b2'] },
      { kind: 'prose', anchor: 'agtrail-saw', titleKey: 'help.agenttrail.saw_t', bodyKeys: ['help.agenttrail.saw_b1'] },
      { kind: 'prose', anchor: 'agtrail-thoughts', titleKey: 'help.agenttrail.thoughts_t', bodyKeys: ['help.agenttrail.thoughts_b1'] },
      { kind: 'prose', anchor: 'agtrail-words', titleKey: 'help.agenttrail.words_t', bodyKeys: ['help.agenttrail.words_b1'] },
      { kind: 'prose', anchor: 'agtrail-receipt', titleKey: 'help.agenttrail.receipt_t', bodyKeys: ['help.agenttrail.receipt_b1'] },
    ],
    qa: [
      { qKey: 'help.agenttrail.q1', aKey: 'help.agenttrail.a1' },
      { qKey: 'help.agenttrail.q2', aKey: 'help.agenttrail.a2' },
      { qKey: 'help.agenttrail.q3', aKey: 'help.agenttrail.a3' },
      { qKey: 'help.agenttrail.q4', aKey: 'help.agenttrail.a4' },
    ],
    seeAlso: ['agent-run', 'agent-undo', 'agent-region'],
  },
  {
    id: 'agent-region',
    group: 'agent',
    titleKey: 'help.agentregion.title',
    ledeKey: 'help.agentregion.lede',
    entryKey: 'help.agentregion.entry',
    figure: { kind: 'surface', surface: 'agent-region', captionKey: 'help.agentregion.figcap' },
    sections: [
      { kind: 'prose', anchor: 'agregion-mark', titleKey: 'help.agentregion.mark_t', bodyKeys: ['help.agentregion.mark_b1'] },
      { kind: 'prose', anchor: 'agregion-inside', titleKey: 'help.agentregion.inside_t', bodyKeys: ['help.agentregion.inside_b1'] },
      { kind: 'prose', anchor: 'agregion-change', titleKey: 'help.agentregion.change_t', bodyKeys: ['help.agentregion.change_b1'] },
      { kind: 'prose', anchor: 'agregion-helpers', titleKey: 'help.agentregion.helpers_t', bodyKeys: ['help.agentregion.helpers_b1'] },
      { kind: 'callout', bodyKey: 'help.agentregion.co1' },
    ],
    qa: [
      { qKey: 'help.agentregion.q1', aKey: 'help.agentregion.a1' },
      { qKey: 'help.agentregion.q2', aKey: 'help.agentregion.a2' },
      { qKey: 'help.agentregion.q3', aKey: 'help.agentregion.a3' },
      { qKey: 'help.agentregion.q4', aKey: 'help.agentregion.a4' },
      { qKey: 'help.agentregion.q5', aKey: 'help.agentregion.a5' },
    ],
    seeAlso: ['region', 'agent-run', 'agent-undo'],
  },
  {
    id: 'agent-trouble',
    group: 'agent',
    titleKey: 'help.agenttrouble.title',
    navKey: 'help.agenttrouble.nav',
    ledeKey: 'help.agenttrouble.lede',
    entryKey: 'help.agenttrouble.entry',
    figure: { kind: 'surface', surface: 'agent-trouble', captionKey: 'help.agenttrouble.figcap' },
    sections: [
      { kind: 'prose', anchor: 'agtrouble-banners', titleKey: 'help.agenttrouble.banners_t', bodyKeys: ['help.agenttrouble.banners_b1', 'help.agenttrouble.banners_b2'], figure: { kind: 'surface', surface: 'agent-banner', captionKey: 'help.agenttrouble.banner_figcap' } },
      { kind: 'prose', anchor: 'agtrouble-waiting', titleKey: 'help.agenttrouble.waiting_t', bodyKeys: ['help.agenttrouble.waiting_b1'] },
      { kind: 'prose', anchor: 'agtrouble-caps', titleKey: 'help.agenttrouble.caps_t', bodyKeys: ['help.agenttrouble.caps_b1'] },
      { kind: 'prose', anchor: 'agtrouble-cost', titleKey: 'help.agenttrouble.cost_t', bodyKeys: ['help.agenttrouble.cost_b1'] },
      { kind: 'prose', anchor: 'agtrouble-storage', titleKey: 'help.agenttrouble.storage_t', bodyKeys: ['help.agenttrouble.storage_b1'] },
    ],
    qa: [
      { qKey: 'help.agenttrouble.q1', aKey: 'help.agenttrouble.a1' },
      { qKey: 'help.agenttrouble.q2', aKey: 'help.agenttrouble.a2' },
      { qKey: 'help.agenttrouble.q3', aKey: 'help.agenttrouble.a3' },
      { qKey: 'help.agenttrouble.q4', aKey: 'help.agenttrouble.a4' },
    ],
    seeAlso: ['agent-setup', 'agent-run'],
  },
  {
    id: 'agent-undo',
    group: 'agent',
    titleKey: 'help.agentundo.title',
    ledeKey: 'help.agentundo.lede',
    entryKey: 'help.agentundo.entry',
    figure: { kind: 'surface', surface: 'agent-undo', captionKey: 'help.agentundo.figcap' },
    sections: [
      { kind: 'prose', anchor: 'agundo-one', titleKey: 'help.agentundo.one_t', bodyKeys: ['help.agentundo.one_b1'] },
      { kind: 'prose', anchor: 'agundo-count', titleKey: 'help.agentundo.count_t', bodyKeys: ['help.agentundo.count_b1'] },
      { kind: 'prose', anchor: 'agundo-cant', titleKey: 'help.agentundo.cant_t', bodyKeys: ['help.agentundo.cant_b1'] },
      { kind: 'prose', anchor: 'agundo-vs', titleKey: 'help.agentundo.vs_t', bodyKeys: ['help.agentundo.vs_b1'] },
    ],
    qa: [
      { qKey: 'help.agentundo.q1', aKey: 'help.agentundo.a1' },
      { qKey: 'help.agentundo.q2', aKey: 'help.agentundo.a2' },
      { qKey: 'help.agentundo.q3', aKey: 'help.agentundo.a3' },
      { qKey: 'help.agentundo.q4', aKey: 'help.agentundo.a4' },
      { qKey: 'help.agentundo.q5', aKey: 'help.agentundo.a5' },
    ],
    seeAlso: ['undo', 'agent-run', 'save'],
  },
];
