/* Save-and-share help descriptors. Copy comes from i18n; figures name rendered examples. */
import type { HelpPage } from '../page-schema';

export const SHARE_PAGES: readonly HelpPage[] = [
  {
    id: 'save',
    group: 'share',
    titleKey: 'help.save.title',
    ledeKey: 'help.save.lede',
    entryKey: 'help.save.entry',
    figure: { kind: 'surface', surface: 'save', captionKey: 'help.save.figcap' },
    sections: [
      { kind: 'prose', anchor: 'save-when', titleKey: 'help.save.when_t', bodyKeys: ['help.save.when_b1', 'help.save.background_b1'] },
      { kind: 'prose', anchor: 'save-return', titleKey: 'help.save.return_t', bodyKeys: ['help.save.return_b1', 'help.save.return_b2'] },
      { kind: 'prose', anchor: 'save-carry', titleKey: 'help.save.carry_t', bodyKeys: ['help.save.carry_b1'] },
      { kind: 'prose', anchor: 'save-caution', titleKey: 'help.save.caution_t', bodyKeys: ['help.save.caution_b1'], figure: { kind: 'surface', surface: 'frame-topright', captionKey: 'help.save.entry_figcap' } },
      { kind: 'callout', bodyKey: 'help.save.co1' },
    ],
    qa: [
      { qKey: 'help.save.q1', aKey: 'help.save.a1' },
      { qKey: 'help.save.q2', aKey: 'help.save.a2' },
      { qKey: 'help.save.q3', aKey: 'help.save.a3' },
      { qKey: 'help.save.q4', aKey: 'help.save.a4' },
    ],
    seeAlso: ['share', 'json', 'planet'],
  },
  {
    id: 'share',
    group: 'share',
    titleKey: 'help.share.title',
    navKey: 'help.share.nav',
    ledeKey: 'help.share.lede',
    entryKey: 'help.share.entry',
    figure: { kind: 'surface', surface: 'share-window', captionKey: 'help.share.window_figcap' },
    sections: [
      { kind: 'prose', anchor: 'share-tabs', titleKey: 'help.share.tabs_t', bodyKeys: ['help.share.tabs_b1'] },
      { kind: 'prose', anchor: 'share-preset', titleKey: 'help.share.preset_t', bodyKeys: ['help.share.preset_b1'], figure: { kind: 'surface', surface: 'export-controls', captionKey: 'help.share.controls_figcap' } },
      { kind: 'prose', anchor: 'share-size', titleKey: 'help.share.size_t', bodyKeys: ['help.share.size_b1'] },
      { kind: 'prose', anchor: 'share-header', titleKey: 'help.sharelook.header_t', bodyKeys: ['help.sharelook.header_b1', 'help.sharelook.attribution_b1'], figure: { kind: 'surface', surface: 'pic-header', captionKey: 'help.sharelook.header_figcap' } },
      { kind: 'prose', anchor: 'share-layers', titleKey: 'help.sharelook.layers_t', bodyKeys: ['help.sharelook.layers_b1'], figure: { kind: 'surface', surface: 'pic-layers', captionKey: 'help.sharelook.layers_figcap' } },
      { kind: 'prose', anchor: 'share-shots', titleKey: 'help.sharelook.shots_t', bodyKeys: ['help.sharelook.shots_b1'], figure: { kind: 'surface', surface: 'pic-shots', captionKey: 'help.sharelook.shots_figcap' } },
      { kind: 'prose', anchor: 'share-notesgrid', titleKey: 'help.sharelook.notes_t', bodyKeys: ['help.sharelook.notes_b1'], figure: { kind: 'surface', surface: 'export-controls-open', captionKey: 'help.sharelook.notes_figcap' } },
      { kind: 'prose', anchor: 'share-footer', titleKey: 'help.sharelook.footer_t', bodyKeys: ['help.sharelook.footer_b1', 'help.sharelook.footer_b2'], figure: { kind: 'surface', surface: 'footer-editor', captionKey: 'help.sharelook.footer_figcap' } },
      { kind: 'prose', anchor: 'share-glyph', titleKey: 'help.share.glyph_t', bodyKeys: ['help.share.glyph_b1', 'help.share.glyph_b2', 'help.share.glyph_b3', 'help.share.textlimit_b1'], figure: { kind: 'surface', surface: 'pic-code', captionKey: 'help.share.glyph_figcap' } },
      { kind: 'prose', anchor: 'share-import', titleKey: 'help.share.import_t', bodyKeys: ['help.share.import_b1'], figure: { kind: 'surface', surface: 'import', captionKey: 'help.share.import_figcap' } },
      { kind: 'prose', anchor: 'share-confirm', titleKey: 'help.share.confirm_t', bodyKeys: ['help.share.confirm_b1'] },
      { kind: 'prose', anchor: 'share-brand', titleKey: 'help.share.brand_t', bodyKeys: ['help.share.brand_b1'], figure: { kind: 'surface', surface: 'pic-brand', captionKey: 'help.share.brand_figcap' } },
      { kind: 'prose', anchor: 'share-preview', titleKey: 'help.sharelook.preview_t', bodyKeys: ['help.sharelook.preview_b1'], figure: { kind: 'surface', surface: 'share', captionKey: 'help.sharelook.figcap' } },
      { kind: 'prose', anchor: 'share-stylize', titleKey: 'help.stylize.enter_t', bodyKeys: ['help.stylize.lede', 'help.stylize.enter_b1'], figure: { kind: 'surface', surface: 'stylize-window', captionKey: 'help.stylize.figcap' } },
      { kind: 'prose', anchor: 'share-stylize-connect', titleKey: 'help.stylize.connect_t', bodyKeys: ['help.stylize.connect_b1'] },
      { kind: 'prose', anchor: 'share-stylize-directions', titleKey: 'help.stylize.directions_t', bodyKeys: ['help.stylize.directions_b1'], figure: { kind: 'surface', surface: 'stylize-directions', captionKey: 'help.stylize.booklet_figcap' } },
      { kind: 'prose', anchor: 'share-stylize-takes', titleKey: 'help.stylize.takes_t', bodyKeys: ['help.stylize.takes_b1'] },
      { kind: 'prose', anchor: 'share-stylize-mark', titleKey: 'help.stylize.mark_t', bodyKeys: ['help.stylize.mark_b1'] },
      { kind: 'callout', bodyKey: 'help.stylize.co1' },
      { kind: 'prose', anchor: 'share-note', titleKey: 'help.share.note_t', bodyKeys: ['help.share.note_b1'] },
      {
        kind: 'keys', anchor: 'share-keys', titleKey: 'help.share.keys_t',
        rows: [
          { doKey: 'help.share.key_image', tokens: [{ kind: 'cmd', id: 'app.export_image' }] },
          { doKey: 'help.share.key_json', tokens: [{ kind: 'cmd', id: 'app.export_json' }] },
        ],
      },
      { kind: 'callout', bodyKey: 'help.share.co1' },
    ],
    qa: [
      { qKey: 'help.share.q1', aKey: 'help.share.a1' },
      { qKey: 'help.share.q2', aKey: 'help.share.a2' },
      { qKey: 'help.share.q3', aKey: 'help.share.a3' },
      { qKey: 'help.share.q4', aKey: 'help.share.a4' },
      { qKey: 'help.sharelook.q3', aKey: 'help.sharelook.a3' },
      { qKey: 'help.stylize.q1', aKey: 'help.stylize.a1' },
      { qKey: 'help.stylize.q2', aKey: 'help.stylize.a2' },
      { qKey: 'help.stylize.q3', aKey: 'help.stylize.a3' },
      { qKey: 'help.stylize.q4', aKey: 'help.stylize.a4' },
    ],
    seeAlso: ['json', 'checklist', 'save', 'agent-intro'],
  },
  {
    id: 'json',
    group: 'share',
    titleKey: 'help.json.title',
    navKey: 'help.json.nav',
    ledeKey: 'help.json.lede',
    entryKey: 'help.json.entry',
    figure: { kind: 'surface', surface: 'json', captionKey: 'help.json.figcap' },
    sections: [
      { kind: 'prose', anchor: 'json-core', titleKey: 'help.json.core_t', bodyKeys: ['help.json.core_b1'] },
      { kind: 'prose', anchor: 'json-sections', titleKey: 'help.json.sections_t', bodyKeys: ['help.json.sections_b1'] },
      { kind: 'prose', anchor: 'json-confirm', titleKey: 'help.share.confirm_t', bodyKeys: ['help.sharelook.attribution_b1', 'help.share.confirm_b1'] },
      { kind: 'prose', anchor: 'json-format', titleKey: 'help.json.format_t', bodyKeys: ['help.json.format_b1'] },
      { kind: 'callout', bodyKey: 'help.json.co1' },
    ],
    qa: [
      { qKey: 'help.json.q1', aKey: 'help.json.a1' },
      { qKey: 'help.json.q2', aKey: 'help.json.a2' },
      { qKey: 'help.json.q3', aKey: 'help.json.a3' },
    ],
    seeAlso: ['share', 'save', 'checklist'],
  },
  {
    id: 'checklist',
    group: 'share',
    titleKey: 'help.checklist.title',
    ledeKey: 'help.checklist.lede',
    entryKey: 'help.checklist.entry',
    figure: { kind: 'surface', surface: 'checklist', captionKey: 'help.checklist.figcap' },
    sections: [
      { kind: 'prose', anchor: 'checklist-what', titleKey: 'help.checklist.what_t', bodyKeys: ['help.checklist.what_b1'] },
      { kind: 'prose', anchor: 'checklist-copy', titleKey: 'help.checklist.copy_t', bodyKeys: ['help.checklist.copy_b1'] },
      { kind: 'prose', anchor: 'checklist-unknown', titleKey: 'help.checklist.unknown_t', bodyKeys: ['help.checklist.unknown_b1'] },
    ],
    qa: [
      { qKey: 'help.checklist.q1', aKey: 'help.checklist.a1' },
      { qKey: 'help.checklist.q2', aKey: 'help.checklist.a2' },
      { qKey: 'help.checklist.q3', aKey: 'help.checklist.a3' },
    ],
    seeAlso: ['share', 'load', 'welcome'],
  },
  {
    id: 'planet',
    group: 'share',
    titleKey: 'help.planet.title',
    ledeKey: 'help.planet.lede',
    entryKey: 'help.planet.entry',
    figure: { kind: 'surface', surface: 'planet', captionKey: 'help.planet.figcap' },
    sections: [
      { kind: 'prose', anchor: 'planet-choose', titleKey: 'help.planet.choose_t', bodyKeys: ['help.planet.choose_b1'] },
      { kind: 'prose', anchor: 'planet-carry', titleKey: 'help.planet.carry_t', bodyKeys: ['help.planet.carry_b1', 'help.planet.carry_b2'] },
      { kind: 'prose', anchor: 'planet-unsaved', titleKey: 'help.planet.unsaved_t', bodyKeys: ['help.planet.unsaved_b1'] },
      { kind: 'callout', bodyKey: 'help.planet.co1' },
    ],
    qa: [
      { qKey: 'help.planet.q1', aKey: 'help.planet.a1' },
      { qKey: 'help.planet.q2', aKey: 'help.planet.a2' },
      { qKey: 'help.planet.q3', aKey: 'help.planet.a3' },
    ],
    seeAlso: ['save', 'share', 'welcome'],
  },
];
